# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D06NDL3E3YYl9_S29kEeU8HT-jiFCA71
"""

a = input().split()
b = [int(x) for x in a]
count=0
for i in range (0,len(b)):
  if b[i]<60:
    count=count+1
print(count)