# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yif-jVelT-VqHJPK_vavfET6X6KZ2tfB
"""

a = input().split()
b = [int(x) for x in a]
count=0
max=b[0]
min=b[0]
for i in range (0,len(b)):
  if b[i]<60:
    count=count+1

  if b[i]>max:
    max=b[i]
  if b[i]<min:
    min=b[i]

print(count)
print(f"max={max} min={min}")
print(count)


if count > 0:
  total = 0
  for i in range(len(b)):
    if b[i] < 60:
      total += b[i]
  avg = total / count
  print(avg)
